"""Helper class for markdown content processing."""
import logging
from datetime import datetime
from typing import List, Optional, Dict, Any

logger = logging.getLogger("nibandha.export.helpers")


class MarkdownProcessor:
    """
    Handles markdown text manipulation operations.
    
    Responsibilities:
    - Remove YAML frontmatter
    - Build unified markdown with frontmatter
    """
    
    @staticmethod
    def remove_frontmatter(content: str) -> str:
        """
        Remove YAML frontmatter from markdown content.
        
        Args:
            content: Markdown content potentially with frontmatter
            
        Returns:
            Content with frontmatter removed
        """
        lines = content.split('\n')
        if lines and lines[0].strip() == '---':
            for i, line in enumerate(lines[1:], 1):
                if line.strip() == '---':
                    return '\n'.join(lines[i+1:])
        return content
    
    @staticmethod
    def build_unified_markdown(
        sections: List[Dict[str, Any]], 
        project_info: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        Build unified markdown document with frontmatter from sections.
        
        Args:
            sections: List of section dictionaries with 'content' key
            project_info: Optional project metadata for frontmatter
            
        Returns:
            Complete markdown document with frontmatter
        """
        if not project_info:
            project_info = {}
        
        # Build frontmatter
        frontmatter = f"""---
title: "Nibandha Quality Report"
subtitle: "Complete Project Analysis"
author: "Generated by Nibandha"
date: "{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
toc: true
lof: true
lot: true
---

"""
        
        # Assemble content
        content = frontmatter
        for section in sections:
            content += f"\n\n---\n\n{section['content']}\n"
        
        return content
