"""
Unified Report Builder - Combines multiple markdown reports into single document.
"""
from pathlib import Path
from typing import List, Dict, Any, Tuple
import logging

logger = logging.getLogger("nibandha.reporting.unified")


class UnifiedReportBuilder:
    """Combines individual markdown reports into unified HTML and DOCX outputs."""
    
    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        self.details_dir = output_dir / "details"
        
    def build_unified_markdown(
        self, 
        summary_path: Path,
        detail_paths: List[Path],
        output_path: Path
    ) -> Path:
        """
        Combine summary and detail reports into single markdown file.
        
        Args:
            summary_path: Path to summary.md
            detail_paths: List of paths to detail reports
            output_path: Where to write unified markdown
            
        Returns:
            Path to generated unified markdown file
        """
        logger.info(f"Building unified markdown from {len(detail_paths) + 1} sections")
        
        sections: List[Tuple[str, str]] = []
        
        # Read summary
        if summary_path.exists():
            summary_content = summary_path.read_text(encoding="utf-8")
            # Remove YAML frontmatter from summary (will add unified one later)
            summary_content = self._remove_frontmatter(summary_content)
            sections.append(("Summary", summary_content))
        
        # Read all detail reports
        for detail_path in detail_paths:
            if detail_path.exists():
                content = detail_path.read_text(encoding="utf-8")
                content = self._remove_frontmatter(content)
                # Extract title from filename
                title = detail_path.stem.replace('_', ' ').title()
                sections.append((title, content))
        
        # Build unified document
        unified_content = self._build_frontmatter()
        
        for title, content in sections:
            # Add page break for DOCX
            unified_content += f"\n\n---\n\n{content}\n"
        
        # Write output
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(unified_content, encoding="utf-8")
        
        logger.info(f"Unified markdown saved to: {output_path}")
        return output_path
    
    def _remove_frontmatter(self, content: str) -> str:
        """Remove YAML frontmatter from markdown."""
        lines = content.split('\n')
        if lines and lines[0].strip() == '---':
            # Find closing ---
            for i, line in enumerate(lines[1:], 1):
                if line.strip() == '---':
                    return '\n'.join(lines[i+1:])
        return content
    
    def _build_frontmatter(self) -> str:
        """Build YAML frontmatter for unified report."""
        from datetime import datetime
        
        return f"""---
title: "Nibandha Quality Report"
subtitle: "Complete Project Analysis"
author: "Generated by Nibandha"
date: "{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
toc: true
lof: true
lot: true
---

"""
    
    def collect_report_paths(self) -> Dict[str, Any]:
        """
        Collect paths to all generated markdown reports.
        
        Returns:
            Dict with 'summary' and 'details' keys
        """
        summary = self.output_dir / "summary.md"
        
        details = []
        if self.details_dir.exists():
            # Maintain specific order for better reading flow
            ordered_names = [
                "unit_report.md",
                "e2e_report.md",
                "type_safety_report.md",
                "complexity_report.md",
                "architecture_report.md",
                "documentation_report.md",
                "module_dependency_report.md",
                "package_dependency_report.md"
            ]
            
            for name in ordered_names:
                path = self.details_dir / name
                if path.exists():
                    details.append(path)
        
        return {
            "summary": summary,
            "details": details
        }
