from typing import Protocol, Any, Dict, Optional

class LoggerProtocol(Protocol):
    """Protocol for loggers to decouple from specific logging implementations."""
    
    def debug(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
    
    def info(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
    
    def warning(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
    
    def error(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
    
    def critical(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
    
    def log(self, level: int, msg: str, *args: Any, **kwargs: Any) -> None: ...
