
# visualization_constants.py

# Dimensions
FIG_SIZE_DEFAULT = (12, 6)
FIG_SIZE_WIDE = (14, 8)
FIG_SIZE_SQUARE = (10, 10)
FIG_SIZE_LARGE = (16, 12)
FIG_SIZE_EXTRA_LARGE = (20, 16)
DPI_DEFAULT = 100
DPI_HIGH = 300

# Colors
COLOR_PASS = "#2ecc71"
COLOR_FAIL = "#e74c3c"
COLOR_WARNING = "#f1c40f"
COLOR_NEUTRAL = "#3498db"
COLOR_TEXT = "black"

COLOR_PALETTE_MAIN = "viridis"
COLOR_PALETTE_CATEGORICAL = "Set3"

# Fonts
FONT_SIZE_TITLE = 14
FONT_SIZE_LABEL = 12
FONT_SIZE_TICK = 10
FONT_SIZE_ANNOTATION = 9
FONT_SIZE_SMALL = 8

# Layout
BAR_WIDTH = 0.5
BAR_WIDTH_THIN = 0.3
ALPHA_DEFAULT = 0.7
ALPHA_TRANSPARENT = 0.5
ALPHA_SOLID = 1.0

ROTATION_X_AXIS = 45
ROTATION_VERTICAL = 90
