# Defaults
DEFAULT_BACKUP_COUNT = 10
DEFAULT_MAX_BYTES = 1024 * 1024 * 5 # 5MB
DEFAULT_ROTATION_INTERVAL_HOURS = 24
DEFAULT_RETENTION_DAYS = 30

# File names
LOG_CONFIG_FILE_YAML = "rotation_config.yaml"
LOG_CONFIG_FILE_JSON = "rotation_config.json"
